GET http://localhost:3001/nikeShoes

###
GET http://localhost:3001/adidasShoes

###

GET http://localhost:3001/underarmourShoes

###
GET http://localhost:5000/shoes

###
GET http://localhost:5000/user/rishabxjain@gmail.com/pass/fdfdhdh

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "first": "testFirst",
    "last": "testLast",
    "email": "testEmail",
    "password": "testPassword"
}

### 
POST http://localhost:5000/cart
Content-Type: application/json

{
    "key": "testFirst",
    "name": "testLast",
    "image_url": "testEmail",
    "site": "testPassword",
    "category": "testPassword",
    "gender": "genderTEst"
}

###
GET http://localhost:5000/cart/test

### 
DELETE http://localhost:5000/cart/test/name/Nike React Vision Men's Shoe